dependencies:
- name: canary-python
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: demo-spring-20190210
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: nodejs-canary
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: stateful-voting-app-worker-java
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.5
- name: voting-app-result-nodejs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: voting-app-result-nodejs-stateful
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: voting-app-vote-python
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: voting-app-worker-java-2stateful
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
- name: voting-app-worker-java-stateful
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
